server:
  port: 8080
  address: 127.0.0.1
  servlet:
      context-path: /api

spring:
  flyway:
    enabled: true
    user: h2user
    password: h2password
    schemas: PUBLIC
    url: jdbc:h2:file:/home/dev/projects/java/alpha/alpha-users-crud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    locations: filesystem:src/main/resources/db/migration
    validate-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:/home/dev/projects/java/alpha/alpha-users-crud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: h2user
    password: h2password
    hikari:
      idle-timeout: 10000
